'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {StoreDB}=require('../store-db');const {createModerationHandler,muteDuration}=require('../moderation-handler');const {createShopHandler}=require('../shop-handler');
function fixture(){const store=new StoreDB(':memory:');store.activate('sales@g.us','demo','owner@c.us','tienda');const config={gruposAutorizados:['sales@g.us'],propietariosGrupos:{'sales@g.us':'owner@c.us'},pagosGrupos:{}};let clock=1000;const sent=[],removed=[];
 const sock={user:{id:'bot:1@s.whatsapp.net'},groupMetadata:async()=>({participants:[{id:'owner@s.whatsapp.net',admin:'admin'},{id:'bot@s.whatsapp.net',admin:'admin'},{id:'helper@s.whatsapp.net'},{id:'buyer@s.whatsapp.net'}]}),sendMessage:async(to,content)=>{sent.push(content);},groupParticipantsUpdate:async(g,ids,action)=>{removed.push({g,ids,action});}};
 const h=createModerationHandler({store,owners:['botowner@c.us'],loadConfig:()=>config,now:()=>clock});
 const msg=(text,who='owner',target='helper',group='sales@g.us')=>({key:{id:text,remoteJid:group,participant:who+'@s.whatsapp.net'},message:{extendedTextMessage:{text,contextInfo:{participant:target+'@s.whatsapp.net'}}}});
 return {store,config,h,sock,msg,sent,removed,setClock:t=>clock=t};}
test('helper assignment and revocation belong only to owner and current group',async()=>{const {store,h,sock,msg}=fixture();await h.handle(sock,msg('.ayudante','buyer'));assert.equal(h.isHelper('sales@g.us','helper@c.us'),false);await h.handle(sock,msg('.ayudante'));assert.equal(h.isHelper('sales@g.us','helper@c.us'),true);assert.equal(h.isHelper('other@g.us','helper@c.us'),false);await h.handle(sock,msg('.quitarayudante'));assert.equal(h.isHelper('sales@g.us','helper@c.us'),false);store.close();});
test('helper can add saldo but cannot subtract, configure payment or stock',async()=>{const {store,h,sock,msg,config}=fixture();await h.handle(sock,msg('.ayudante'));const shop=createShopHandler({store,loadConfig:()=>config,saveConfig:()=>{},loadBalances:()=>({}),superAdmins:[],download:async()=>[],isHelper:h.isHelper});await shop.handle(sock,msg('/s 10','helper','buyer'));assert.equal(store.balance('sales@g.us','buyer@c.us'),1000);await shop.handle(sock,msg('-s 5','helper','buyer'));assert.equal(store.balance('sales@g.us','buyer@c.us'),1000);await shop.handle(sock,msg('/setpago BANK','helper'));assert.equal(store.shop('sales@g.us').payment,'');await h.handle(sock,msg('.mute 10m','helper','buyer'));assert.equal(store.db.prepare('SELECT COUNT(*) n FROM mutes').get().n,1);await h.handle(sock,msg('.unmute','helper','buyer'));assert.equal(store.db.prepare('SELECT COUNT(*) n FROM mutes').get().n,0);store.close();});
test('helper may kick regular members but cannot kick owner or appoint helpers',async()=>{const {store,h,sock,msg,removed}=fixture();await h.handle(sock,msg('.ayudante'));await h.handle(sock,msg('.kick','helper','owner'));assert.equal(removed.length,0);await h.handle(sock,msg('.ayudante','helper','buyer'));assert.equal(h.isHelper('sales@g.us','buyer@c.us'),false);await h.handle(sock,msg('.kick','helper','buyer'));assert.equal(removed.length,1);store.close();});
test('mute deletes every incoming message until expiry, unmute clears it',async()=>{const {store,h,sock,msg,sent,setClock}=fixture();await h.handle(sock,msg('.mute 10m','owner','buyer'));const media=msg('','buyer');media.message={stickerMessage:{}};assert.equal(await h.handle(sock,media),true);assert.ok(sent.at(-1).delete);setClock(601001);assert.equal(await h.handle(sock,media),false);await h.handle(sock,msg('.mute 1h','owner','buyer'));await h.handle(sock,msg('.unmute','owner','buyer'));assert.equal(await h.handle(sock,media),false);store.close();});
test('mute durations and bot admin role are validated',async()=>{assert.equal(muteDuration('10m'),600000);for(const s of ['0m','31d','-1h','1.5h'])assert.throws(()=>muteDuration(s));const {store,h,sock,msg}=fixture();const metadata=sock.groupMetadata;sock.groupMetadata=async()=>{const m=await metadata();m.participants[1].admin=null;return m;};await h.handle(sock,msg('.mute 10m','owner','buyer'));assert.equal(store.db.prepare('SELECT COUNT(*) n FROM mutes').get().n,0);store.close();});
