'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {StoreDB}=require('../store-db');const {createRentalHandler,duration,EXPIRED}=require('../rental-handler');
function setup(){const store=new StoreDB(':memory:');let clock=1000;const config={gruposAutorizados:[],propietariosGrupos:{}};const sent=[];
 const h=createRentalHandler({store,owners:['botowner@c.us'],loadConfig:()=>config,saveConfig:()=>{},now:()=>clock});
 const sock={groupMetadata:async()=>({participants:[{id:'tenant@s.whatsapp.net',admin:'admin'},{id:'customer@s.whatsapp.net'}]}),sendMessage:async(to,p)=>{sent.push({to,...p});}};
 const msg=(text,who='tenant',chat='sales@g.us')=>({key:{remoteJid:chat,participant:chat.endsWith('@g.us')?who+'@s.whatsapp.net':undefined},message:{conversation:text}});
 return {store,h,config,sock,sent,msg,setClock:t=>clock=t};}
test('duration requires bounded positive explicit units',()=>{assert.equal(duration('1 día'),86400000);assert.equal(duration('2 horas'),7200000);for(const s of ['0 dias','-1 dia','367 dias','1 mes','1.5 dias'])assert.throws(()=>duration(s));});
test('one-use key binds one customer/group and expiry blocks immediately',()=>{const {store,h,setClock}=setup();const key=h.issue('1 minuto');assert.equal(h.redeem(key,'sales@g.us','tenant@c.us'),61000);assert.equal(h.allowed('sales@g.us'),true);assert.equal(h.allowed('other@g.us'),false);assert.throws(()=>h.redeem(key,'other@g.us','tenant@c.us'));setClock(61000);assert.equal(h.allowed('sales@g.us'),false);assert.throws(()=>h.redeem(h.issue('1 dia'),'sales@g.us','other@c.us'));store.close();});
test('only bot owner privately generates keys, group customer cannot redeem',async()=>{const {store,h,sock,msg,sent}=setup();await h.handle(sock,msg('/genkey 1 dia','tenant','tenant@s.whatsapp.net'));assert.equal(store.db.prepare('SELECT COUNT(*) n FROM rental_keys').get().n,0);await h.handle(sock,msg('/genkey 1 dia','botowner','botowner@s.whatsapp.net'));assert.equal(store.db.prepare('SELECT COUNT(*) n FROM rental_keys').get().n,1);const key=h.issue('1 dia');await h.handle(sock,msg('/activar '+key,'customer'));assert.equal(h.allowed('sales@g.us'),false);store.close();});
test('expiry notifies both groups once and preserves inventory',async()=>{const {store,h,sock,setClock,sent}=setup();store.activate('sales@g.us','demo','tenant@c.us','tienda');store.link('sales@g.us','admin@g.us');store.product('sales@g.us','gift',10,'Gift');store.add('sales@g.us','gift',{text:'CODE'},null,'fp','source');h.redeem(h.issue('1 minuto'),'sales@g.us','tenant@c.us');setClock(61001);await h.tick(sock);await h.tick(sock);assert.equal(sent.length,2);assert.ok(sent.every(s=>s.text===EXPIRED));assert.equal(h.allowed('admin@g.us'),false);assert.equal(store.inventory('sales@g.us')[0].quantity,1);store.close();});
test('owner suspends by alias privately and fresh key restores same tenant',async()=>{const {store,h,sock,msg,sent}=setup();store.activate('sales@g.us','demo','tenant@c.us','tienda');h.redeem(h.issue('1 dia'),'sales@g.us','tenant@c.us');await h.handle(sock,msg('/suspender demo','botowner','botowner@s.whatsapp.net'));assert.equal(h.allowed('sales@g.us'),false);assert.equal(await h.handle(sock,msg('.actram demo')),true);assert.equal(await h.handle(sock,msg('/s 100')),true);h.redeem(h.issue('1 minuto'),'sales@g.us','tenant@c.us');assert.equal(h.allowed('sales@g.us'),true);store.close();});
test('group activation authorizes tenant but never grants global vendor permissions',async()=>{const {store,h,sock,msg,config}=setup();await h.handle(sock,msg('/activar '+h.issue('1 dia')));assert.deepEqual(config.gruposAutorizados,['sales@g.us']);assert.equal(config.propietariosGrupos['sales@g.us'],'tenant@c.us');assert.equal(config.vendedores,undefined);store.close();});
