[phases.setup]
nixPkgs = [
    "glib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "cups",
    "dbus",
    "libdrm",
    "libxkbcommon",
    "libxcomposite",
    "libxdamage",
    "libxfixes",
    "libxrandr",
    "mesa",
    "pango",
    "cairo",
    "alsa-lib",
    "expat",
    "systemd"
]
